#!/usr/bin/env python3
"""Bundle index.html + all local JS files + woff2 fonts into a single
self-contained standalone.html.

Motivation: Page Host's "download" gives you just index.html, without
the sibling js/ and assets/ folders it references — so opening the
downloaded file locally leaves the wizard broken (JS 404s → "Detecting
mode…" stuck, preview iframe blank). This bundler inlines everything
so `standalone.html` works from file:// too.

Usage:
    python3 build-standalone.py

Reads: index.html, ./js/*.js, ./assets/fonts/*.woff2
Writes: ./standalone.html
"""

from __future__ import annotations
import base64
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
INDEX = ROOT / "index.html"
OUTPUT = ROOT / "standalone.html"


def resolve(relative: str) -> Path:
    """Resolve a ./-prefixed path relative to the repo root."""
    return (ROOT / relative.lstrip("./")).resolve()


def inline_font(match: re.Match[str]) -> str:
    """Replace `url('./assets/fonts/X.woff2')` with a base64 data URL."""
    rel = match.group(1)
    path = resolve(rel)
    if not path.exists():
        print(f"  ⚠ font not found: {rel} — leaving reference intact")
        return match.group(0)
    b64 = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"url('data:font/woff2;base64,{b64}')"


def inline_script(match: re.Match[str]) -> str:
    """Replace `<script src="./js/X.js?v=...">` with an inline <script> block."""
    src = match.group(1)
    path_part = src.split("?", 1)[0]
    path = resolve(path_part)
    if not path.exists():
        print(f"  ⚠ script not found: {src} — leaving reference intact")
        return match.group(0)
    js = path.read_text(encoding="utf-8")
    # Guard against any accidental </script> inside string literals or regex
    # (the JS files don't currently contain them, but this keeps us safe).
    js = js.replace("</script>", "<\\/script>")
    return f"<script>\n// ==== inlined from {path_part} ====\n{js}\n</script>"


def main() -> None:
    html = INDEX.read_text(encoding="utf-8")

    # 1) Inline @font-face url('./assets/fonts/*.woff2') references
    font_pattern = re.compile(r"url\('(\./assets/fonts/[^']+\.woff2)'\)")
    fonts_before = len(font_pattern.findall(html))
    html = font_pattern.sub(inline_font, html)
    print(f"✓ Inlined {fonts_before} font file(s)")

    # 2) Inline <script src="./js/*.js"></script> references
    #    (Leaves external CDNs like https://cdn.tailwindcss.com untouched.)
    script_pattern = re.compile(r'<script\s+src="(\./[^"]+\.js[^"]*)"\s*></script>')
    scripts_before = len(script_pattern.findall(html))
    html = script_pattern.sub(inline_script, html)
    print(f"✓ Inlined {scripts_before} script file(s)")

    # 3) Header comment so future readers understand what this is
    banner = (
        "<!--\n"
        "  standalone.html — auto-generated by build-standalone.py.\n"
        "  Do not edit directly; edit index.html + js/*.js and rerun the bundler.\n"
        "  This single file inlines every JS module and font as base64 so it\n"
        "  works from file:// or any static host without sibling files.\n"
        "-->\n"
    )
    if not html.lstrip().startswith("<!--"):
        html = banner + html
    else:
        # Replace any existing banner (only if it looks like ours)
        html = re.sub(r"^\s*<!--\s*standalone\.html[\s\S]*?-->\n", banner, html, count=1)
        if banner not in html:
            html = banner + html

    OUTPUT.write_text(html, encoding="utf-8")
    size_kb = OUTPUT.stat().st_size / 1024
    print(f"✓ Wrote {OUTPUT.name} ({size_kb:,.1f} KB)")


if __name__ == "__main__":
    main()
